### ISSUE TITLE
Apply pundit_role to an argument that is part of an InputObject

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#2465]
Is it possible to apply a `pundit_role` to an `argument` that is part of an `InputObject`?  

```ruby
class Inputs::PersonInput < Types::BaseInputObject

  argument :is_cool, Boolean, required: false, 
    pundit_role: :already_very_cool

end
```

I have other `argument`s working spectacularly with the `pundit_role` directive but not inside of `InputObject`.  I am thinking that if it is, somehow the mutation would have to pass along information about the `Type` or the `Policy` in order for this to work ... if it's able to work at all.

**Comment by rmosolgo** [comment]
It _should_ just work if you set up the `argument_class(...)` configuration as shown in the docs: https://graphql-ruby.org/authorization/pundit_integration.html#authorizing-arguments

Does that work for you? What happens when you try it?

**Comment by rmosolgo** [comment]
Thanks for sharing those details! Yes, it definitely makes sense. Maybe it's a bug, let me take a look and follow up here.

**Comment by nesrual** [comment]
+1

I have the same problem. Exact same setup.

**Comment by chadwtaylor** [comment]
+1 

Looking forward to the fix.

**Comment by rmosolgo** [comment]
Hi, sorry for the slow turn-around on this, and thanks for the bumps here. I've just released graphql `1.9.13` and graphql-pro `1.10.8` which should fix this. Please update to those versions and give it another go, and let me know if you run into any other trouble!

**Comment by thornomad** [comment]
Thanks for working on this!

I updated to the latest version and after adding `def self.pundit_policy_class` to my `PersonInput` (from the example in my comment above) I can confirm now that _the policy is now being called via the input_!  👍 

**However:** I think I am still missing another piece of this puzzle (I went over the docs again but didn't see it).  

While the pundit policy is being called ... the `record` that is being passed to `PersonPolicy` from the `PersonInput` is not the _actual_ `person` object—instead, the `record` that `PersonPolicy` receives is the `PersonUpdate` mutation itself.

### how to get the actual record to the argument inside the input?

Inside the `PersonMutation`, the `id` argument has the information about the `record` specified explicitly (and pundit gets it):

```ruby
# app/graphql/mutations/person_update.rb

# this defines what the `record` will be explicitly
argument :id, ID, required: true,
  as: :person, loads: Types::PersonType, 
  pundit_role: :update # it passes the record loaded via the id to pundit
```

However, back inside my `PersonInput` class: how do I tell that argument to also use the same record that was loaded by the `:id` argument from the mutation?

```ruby
# app/graphql/inputs/person_input.rb
class Inputs::PersonInput < Types::BaseInputObject
  # how can I get this argument to identify the correct `record` to pass to pundit?
  argument :is_cool, Boolean, required: false, pundit_role: :already_cool
end

  def self.pundit_policy_class
    ::PersonPolicy
  end
end
```

I took a look at the additions here and am not seeing how it would be able to discover the hidden `record` that is specified by the `id` argument: https://github.com/rmosolgo/graphql-ruby/blob/ca7e303385ef0d6ffb295e2b8fca772106b03352/lib/graphql/schema/argument.rb#L96-L108

**Comment by rmosolgo** [comment]
Thanks for the details on that, @thornomad . It required a bigger shift, actually a breaking change to graphql-ruby. Previously, argument values weren't included at all in the authorization system. Now, they're passed down as arguments to `.authorized?` methods, which was a breaking change. I've put this change on the 1.10-dev branch: https://github.com/rmosolgo/graphql-ruby/pull/2520

I've just released 1.10.0.pre1, which includes those changes [as well as others](https://github.com/rmosolgo/graphql-ruby/blob/1.10-dev/CHANGELOG.md#1100pre1-10-oct-2019), and graphql-pro 1.11.0, which should take advantage of that new behavior. 

Can you give those a try and let me know how it goes?

**Comment by thornomad** [comment]
Hi @rmosolgo - I just updated to the `1.10-pre` version and it seems to be working now as expected!  Thanks for digging into this and finding a solution.  Onward!

**Comment by gopeter** [comment]
Dear @rmosolgo and @thornomad,

I've got the same problem today and updated to `graphql 1.10.0.pre1` and `graphql-pro 1.11.0`, but trying to read the record from the input argument still resolves to the mutation and not the record itself.

```ruby
# app/graphql/mutations/user/update.rb

module Mutations
  module User
    class Update < Inputs
      graphql_name 'UpdateUser'
      pundit_role nil

      argument :id, ID, required: true, loads: Types::UserType, pundit_role: :can_update
      field :user, Types::UserType, null: true

      def load_id(user_id)
        Helpers::GlobalId.find_record(model: ::User, id: user_id)
      end

      def resolve(inputs)
        inputs = Helpers::GlobalId.force_database_ids(fields: inputs)
        Functions::Mutate.new(model: ::User, record: inputs[:id], fields: inputs.except(:id)).update
      end
    end
  end
end
```

```ruby
# app/graphql/mutations/user/inputs.rb

module Mutations
  module User
    class Inputs < Base
      argument :username, String, required: false
      argument :is_admin, Boolean, required: false, pundit_role: :can_set_admin
    end
  end
end
```

```ruby
# app/policies/user_policy.rb

class UserPolicy < ApplicationPolicy
  def is_admin?
    user.is_admin?
  end

  def can_create?
    user.is_admin?
  end

  def can_update?
    user.is_admin? || record.id == user.id
  end

  def can_set_admin?
      # a user can't remove it's own admin rights
      user.is_admin? && record.id != user.id
  end

  def can_delete?
    user.is_admin? && record.id != user.id
  end
end
```

I've expected to get the real record in my `can_set_admin?` method, but I get the mutation object instead.

Anything that I've missed?
