### ISSUE TITLE
Connections in 1.10.3 still returning incorrect result for hasNextPage

### ISSUE THREAD

**Issue by evancloutier** [rmosolgo/graphql-ruby#2793]
👋 I'm trying to upgrade to ^1.10 to make use of the new connections implementation, but I'm still seeing incorrect results for `hasNextPage` being returned, depending on if a `first` variable is provided to my query.

I have no need for a custom connection class yet, so I'm a bit stumped as to what could be going on (or if I'm missing something?)

```ruby
class IvyServiceSchema < GraphQL::Schema
  default_max_page_size 50

  mutation(Types::MutationType)
  query(Types::QueryType)

  use GraphQL::Pagination::Connections
  use GraphQL::Batch

   ...
end
```

```ruby
class Types::QueryType < Types::BaseObject
  field :community_feed, Types::Models::TaskType.connection_type, null: true do
    argument :category, String, required: true
    argument :date, String, required: true
  end

  ...
end
```

Where performing:
```javascript
{
  communityFeed(date: "02-03-2020", category: "self") { 
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```
Results in:
```javascript
{
  "data": {
    "communityFeed": {
      "pageInfo": {
        "hasNextPage": false,
        "endCursor": "NTA"
      }
    }
  }
}
```

And including `first: 50` in the communityFeed query will flip the `hasNextPage` result to true.

**Comment by rmosolgo** [comment]
Ick, sorry to hear it! Thanks for reporting it. Let me take a look.

**Comment by modosc** [comment]
i guess this wasn't resolved in #1109  ?

**Comment by rmosolgo** [comment]
Well, it was fixed for at least one case (https://github.com/rmosolgo/graphql-ruby/issues/2707#issuecomment-579845750)

It's _supposed_ to be covered by this unit test:

https://github.com/rmosolgo/graphql-ruby/blob/21d260294f9ebd16bcfade42136264cc18e04404/spec/support/connection_assertions.rb#L194-L198

@evancloutier, what kind of object does `def community_feed` return? An ActiveRecord relation, or something else? 

Could you add some debug info to that field, then re-run a broken query and tell me what it prints out? 

```ruby 
def community_field(...)
  result = begin
    # put previous implementation here 
  end 
  p "returning: #{result.class}"
  p "connections configured? #{IvyServiceSchema.new_connections?}"
  p "runtime connections configured? #{context.schema}, #{context.schema.new_connections?}"
  p "registered wrappers: #{context.schema.connections.all_wrappers}"
  result 
end 
```

Maybe something isn't coming through right. Are you using the new `Execution::Interpreter` module?

**Comment by modosc** [comment]
> Well, it was fixed for at least one case (#2707 (comment))

i'm in the middle of porting/removing our monkeypatch for this now, i can also help debug locally.

**Comment by modosc** [comment]
it looks like it's handled correctly here:

https://github.com/rmosolgo/graphql-ruby/blob/e881fc30760f6724ddbb627d66f0ee2e2e98def5/lib/graphql/pagination/connection.rb#L69

but not in these places:
https://github.com/rmosolgo/graphql-ruby/blob/1a21f665554a00c822b8f5212b2900e64ec17a91/lib/graphql/relay/array_connection.rb#L36
https://github.com/rmosolgo/graphql-ruby/blob/5ebcb739daeae914bbc4b12e0e1a3ba0d6a0b9fc/lib/graphql/relay/relation_connection.rb#L52
https://github.com/rmosolgo/graphql-ruby/blob/e881fc30760f6724ddbb627d66f0ee2e2e98def5/lib/graphql/relay/base_connection.rb#L82

unfortunately i've got references to all sorts of connection classes right now, trying to work through which ones are which. should all of the `#first` methods work the same?

**Comment by evancloutier** [comment]
@rmosolgo Thanks for the quick reply! Here is the debug information you've requested:

```
"returning: Task::ActiveRecord_Relation"
"connections configured? true"
"runtime connections configured? #<IvyServiceSchema:0x00007f96638f6f00>, false"
undefined method `all_wrappers' for nil:NilClass
```

I'm not aware of the new `Execution::Interpreter` module, so I think not, unless its configured by default.

I'm in the midst of upgrading to Pro at the moment as well to take advantage of stable cursors, but FWIW the same problem still exists (debug output above is on my master, pro-less branch).

**Comment by rmosolgo** [comment]
thanks, this is the ticket: 

```
"runtime connections configured? #<MySchema:0x00007f96638f6f00>, false"
```

It looks like the new pagination system isn't being properly handed to the old runtime. I'll fix it.

**Comment by evancloutier** [comment]
@rmosolgo Is there a way to upgrade to this new runtime? I didn't realize I was on the old one 🤔

**Comment by rmosolgo** [comment]
It's here: https://graphql-ruby.org/queries/interpreter.html I'd worry about that _next_ though 😛 

Could you try bundling master and see if it works better for you? 

```ruby 
gem "graphql", github: "rmosolgo/graphql-ruby"
```

Let me know how it goes! I think #2798 should have done the trick.

**Comment by evancloutier** [comment]
@rmosolgo Problem solved! Thanks for getting this fixed so quickly 🎉
