### ISSUE TITLE
Triggering subscription leads to NoMethodError

### ISSUE THREAD

**Issue by chadwilken** [rmosolgo/graphql-ruby#3357]
**Describe the bug**
We are triggering subscriptions and receive `NoMethodError: undefined method `[]' for nil:NilClass`. On my limited digging into the pro code, it seems that it is when it attempts to access the `context` of the subscription and it is `nil`.

**Versions**
`graphql (1.12.5)`
`graphql-pro (1.17.7)`
`graphql-batch (0.4.2)`
`rails (6.0.3.4)`

**GraphQL schema**
```ruby
# schema.rb
class Schema < GraphQL::Schema
  use GraphQL::Batch
  use GraphQL::Tracing::ScoutTracing
  use GraphQL::Pro::PusherSubscriptions, redis: Redis.new(url: Rails.application.config.graphql_subscription_redis_url)

  tracer Tracers::DatabaseConnectionTracer.new

  mutation Types::MutationType
  query Types::QueryType
  subscription Types::SubscriptionType
  cursor_encoder CursorEncoder

  default_max_page_size 100

  instrument :query, Instrumentations::RestrictMutationsToPayingCustomers

end

# database_connection_tracer.rb
module Tracers
  class DatabaseConnectionTracer
    EVENT_NAME = 'execute_multiplex'.freeze

    def trace(event, data)
      if event == EVENT_NAME
        multiplex = data[:multiplex]

        role = multiplex.queries.all?(&:query?) ?
          ActiveRecord::Base.reading_role :
          ActiveRecord::Base.writing_role

        ActiveRecord::Base.connected_to(role: role) do
          yield
        end
      else
        yield
      end
    end
  end
end


# graphql_controller.rb
...
def execute
  context = {
    current_user: current_user,
    current_company: current_company,
    channel_prefix: "private-user-#{current_user&.id}-",
    subscription_scope_id: current_company&.id,
    ip_address: request_ip_address,
    authorize: ->(record, query) { authorize(record, query) }
  }

  CompanyCamSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
end

# subscription_type.rb
module Types
  class SubscriptionType < BaseObject
    graphql_name 'Subscription'
    description 'The subscription root'

    field :asset_deleted, subscription: Subscriptions::AssetDeleted, subscription_scope: :subscription_scope_id
    field :asset_processed, subscription: Subscriptions::AssetProcessed, subscription_scope: :subscription_scope_id
    field :asset_reassigned, subscription: Subscriptions::AssetReassigned, subscription_scope: :subscription_scope_id
    field :asset_status_changed, subscription: Subscriptions::AssetStatusChanged, subscription_scope: :subscription_scope_id
    field :notification_created, subscription: Subscriptions::NotificationCreated, subscription_scope: :subscription_scope_id
    field :video_static_renditions_ready, subscription: Subscriptions::VideoStaticRenditionsReady, subscription_scope: :subscription_scope_id

  end
end

# base_subscription.rb
module Subscriptions
  class BaseSubscription < GraphQL::Schema::Subscription
    include GraphQL::Pro::PunditIntegration::ObjectIntegration

    object_class Types::BaseObject
    field_class Fields::BaseField
    argument_class Types::BaseArgument

    pundit_role nil
  end
end
```

**Steps to reproduce**

- Have a user subscribe to the given subscription field
- `trigger` said subscription
In our case this looks like:
```ruby
CompanyCamSchema.subscriptions.trigger('assetReassigned', { feedable_id: feedable_id }, feedItem, scope: company.id)
```
- Receive error

**Expected behavior**

It doesn't throw an error if the `context` is `nil`.

**Actual behavior**
- It throws an exception.

<details>
<summary>Click to view exception backtrace</summary>

```
    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/subscriptions.rb:130 :in `block in filter_still_subscribed`
    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/subscriptions.rb:129 :in `each`
    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/subscriptions.rb:129 :in `filter_still_subscribed`
    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/subscriptions.rb:57 :in `block in execute_all_with_backwards_compat`
    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/subscriptions/redis_storage.rb:273 :in `block in each_fingerprint_and_subscription_ids`
    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/subscriptions/redis_storage.rb:260 :in `each`

    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/subscriptions/redis_storage.rb:260 :in `each_with_index`
    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/subscriptions/redis_storage.rb:260 :in `each_fingerprint_and_subscription_ids`
    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/subscriptions.rb:51 :in `execute_all_with_backwards_compat`
    [GEM_ROOT]/gems/graphql-pro-1.17.7/lib/graphql/pro/pusher_subscriptions.rb:24 :in `execute_all`
    [GEM_ROOT]/gems/graphql-1.12.5/lib/graphql/subscriptions.rb:87 :in `trigger`
    [PROJECT_ROOT]/app/interactors/subscriptions/base_interactor.rb:18 :in `deliver_subscription`
    [PROJECT_ROOT]/app/interactors/subscriptions/assets/processed_interactor.rb:15 :in `block (2 levels) in call`
    [PROJECT_ROOT]/app/interactors/subscriptions/assets/processed_interactor.rb:14 :in `each`
    [PROJECT_ROOT]/app/interactors/subscriptions/assets/processed_interactor.rb:14 :in `block in call`
    [PROJECT_ROOT]/app/interactors/subscriptions/base_interactor.rb:43 :in `with_asset_parents`
    [PROJECT_ROOT]/app/interactors/subscriptions/assets/processed_interactor.rb:13 :in `call`
    [GEM_ROOT]/gems/interactor-3.1.1/lib/interactor.rb:143 :in `block in run!`
    [GEM_ROOT]/gems/interactor-3.1.1/lib/interactor/hooks.rb:213 :in `block in with_hooks`
    [GEM_ROOT]/gems/interactor-3.1.1/lib/interactor/hooks.rb:224 :in `run_around_hooks`
    [GEM_ROOT]/gems/interactor-3.1.1/lib/interactor/hooks.rb:211 :in `with_hooks`
    [GEM_ROOT]/gems/interactor-3.1.1/lib/interactor.rb:142 :in `run!`
    [GEM_ROOT]/gems/interactor-3.1.1/lib/interactor.rb:115 :in `run`
    [GEM_ROOT]/gems/interactor-3.1.1/lib/interactor.rb:50 :in `tap`
    [GEM_ROOT]/gems/interactor-3.1.1/lib/interactor.rb:50 :in `call`
    [PROJECT_ROOT]/app/listeners/graphql/subscription_listener.rb:11 :in `asset_processed`
    [GEM_ROOT]/gems/wisper-sidekiq-1.3.0/lib/wisper/sidekiq.rb:18 :in `public_send`
    [GEM_ROOT]/gems/wisper-sidekiq-1.3.0/lib/wisper/sidekiq.rb:18 :in `perform`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185 :in `execute_job`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167 :in `block (2 levels) in process`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-status-1.1.1/lib/sidekiq-status/server_middleware.rb:42 :in `call`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130 :in `block in invoke`
    [GEM_ROOT]/gems/scout_apm-2.6.7/lib/scout_apm/background_job_integrations/sidekiq.rb:68 :in `call`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-pro-4.0.5/lib/sidekiq/batch/middleware.rb:56 :in `call`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130 :in `block in invoke`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133 :in `invoke`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166 :in `block in process`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137 :in `block (6 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108 :in `local`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136 :in `block (5 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43 :in `block in call`
    [GEM_ROOT]/gems/activesupport-6.0.3.4/lib/active_support/execution_wrapper.rb:88 :in `wrap`
    [GEM_ROOT]/gems/activesupport-6.0.3.4/lib/active_support/reloader.rb:72 :in `block in wrap`
    [GEM_ROOT]/gems/activesupport-6.0.3.4/lib/active_support/execution_wrapper.rb:88 :in `wrap`
    [GEM_ROOT]/gems/activesupport-6.0.3.4/lib/active_support/reloader.rb:71 :in `wrap`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42 :in `call`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132 :in `block (4 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243 :in `stats`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127 :in `block (3 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8 :in `call`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126 :in `block (2 levels) in dispatch`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73 :in `global`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125 :in `block in dispatch`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48 :in `with_context`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42 :in `with_job_hash_context`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124 :in `dispatch`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165 :in `process`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83 :in `process_one`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71 :in `run`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16 :in `watchdog`
    [GEM_ROOT]/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25 :in `block in safe_thread`
```

</details>

**Additional context**
Best I can tell is that the user went idle so Pusher cleaned up the connection but it's hard to reproduce when trying, granted we have plenty of errors in Honeybadger from it.

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I'll take a look soon and follow up here.

**Comment by rmosolgo** [comment]
It turned out to be exactly the error you spotted -- when I refactored that code to make batch reads of subscription data, I forgot about the possibility of this race condition 😖  Thanks again for reporting this, fixed in 1.17.8 👍  Please let me know if you run into anymore trouble with it.

**Comment by sajjadmurtaza** [comment]
@chadwilken @rmosolgo  what is `execute_multiplex` here?

**Comment by rmosolgo** [comment]
A multiplex is one or more GraphQL queries, executed concurrently: https://graphql-ruby.org/queries/multiplex.html

Under the hood, all queries are executed inside a multiplex (even if it's a multiplex of size _one_). Because of that, `execute_multiplex` is the top-level execution event in `GraphQL::Tracing` -- _all_ execution happens during `yield` for that event.

**Comment by xiaoxipang** [comment]
Hey @rmosolgo, did we merge this change in the graphql 2.0? I updated my gem to 2.0.12 but I still get the same error.
`NoMethodError · undefined method `trigger' for nil:NilClass` where I'm calling `MySchema.subscriptions.trigger(...)`

**Comment by rmosolgo** [comment]
@xiaoxipang , this bug was fixed in GraphQL-Pro 1.17.8 last year. If you're encountering a bug, please open a new issue with a detailed report and we can look into it!
