### ISSUE TITLE
Issues loading with new rails app starting with graphql-ruby version 1.13.7

### ISSUE THREAD

**Issue by mckaysalisbury** [rmosolgo/graphql-ruby#3887]
**Describe the bug**
When using the latest versions of graphql-ruby, `/Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/field.rb:282:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)` is thrown.

**Versions**

`graphql` version: 1.13.7 and 1.13.8 (This problem does not occur in 1.13.6 and older)
`rails` (or other framework): 5.2.6 (probably exists in other versions?)

**Steps to reproduce**

```
rails new repro
cd repro
bundle install
bundle exec rails c # This loads without error, I then pressed <ctrl>+d to exit
echo gem \'graphql\' >> Gemfile # specifying versions older than 1.13.7 does not exhibit the errant behavior
bundle install
bundle exec rails c # This generates an error
```

**Expected behavior**
I expected the console to load both times.

**Actual behavior**
It failed to load after graphql is installed.

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
mckaysailsbury@McKay-Salisburys-MacBook-Pro repro % bundle exec rails c             
/Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/field.rb:282:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/member/accepts_definition.rb:154:in `initialize'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/field.rb:129:in `new'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/field.rb:129:in `from_options'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/member/has_fields.rb:12:in `field'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/resolver/has_payload_type.rb:54:in `field'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/mutation.rb:71:in `field'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/relay_classic_mutation.rb:25:in `<class:RelayClassicMutation>'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/relay_classic_mutation.rb:23:in `<class:Schema>'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/relay_classic_mutation.rb:5:in `<module:GraphQL>'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema/relay_classic_mutation.rb:4:in `<top (required)>'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql/schema.rb:51:in `<top (required)>'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/graphql-1.13.8/lib/graphql.rb:113:in `<top (required)>'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
	from /Users/mckaysailsbury/src/monolith/garbage/repro/config/application.rb:7:in `<top (required)>'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/mckaysailsbury/.rbenv/versions/2.5.7/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'
```

</details>

**Additional context**
This problem does not occur in 1.13.6 and older. We only noticed it in the newer versions.

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I'll take a look and follow up here in a bit.

**Comment by rmosolgo** [comment]
I gave it a try on Ruby 3.1.0 and Rails 7 and it went alright: 

```
rails new graphql_boom_test
cd graphql_boom_test
bundle add graphql --version 1.13.8
be rails c 
# Loading development environment (Rails 7.0.1)
irb(main):001:0> GraphQL
# => GraphQL
irb(main):002:0> GraphQL::Schema::RelayClassicMutation
# => GraphQL::Schema::RelayClassicMutation
```

I also tried on Ruby 2.7.3 and it worked fine: 

```
~/code/graphql_boom_test $ ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin19]
~/code/graphql_boom_test $ be rails c
Loading development environment (Rails 7.0.1)
irb(main):001:0> GraphQL::Schema::RelayClassicMutation
=> GraphQL::Schema::RelayClassicMutation
irb(main):002:0> quit
```

But I see you're Ruby 2.5.7 and Rails 5.2.6. I tried getting that going on my local, but it's hung up on nokogiri: 

```
~/code $ gem install nokogiri --platform="x86_64-darwin19"
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.1-x64-unknown.gemspec.rz)
```

For some reason, it's not finding my platform, even when I provide it 😖 

I also reviewed the diff (https://github.com/rmosolgo/graphql-ruby/compare/v1.13.6...v1.13.7) and didn't come up with any hints of why it started breaking there. 

Here's where the NoMethodError comes from: 

https://github.com/rmosolgo/graphql-ruby/blob/a4cfb6a391d64b6912440c075eb3236e36c28f5f/lib/graphql/schema/field.rb#L282

`arguments` is supposed to be an empty list when it's not passed (wayyyy at the end of this long line): 

https://github.com/rmosolgo/graphql-ruby/blob/a4cfb6a391d64b6912440c075eb3236e36c28f5f/lib/graphql/schema/field.rb#L216

Since it works fine on newer Rubies, my first hunch is that there's a keyword argument ... difference ... in Ruby 2.5.x. (That feature of Ruby received a lot of work, getting ready for Ruby 3.0). Any chance you could try your set up on a more recent Ruby and see if it's "fixed" in that case?

**Comment by mckaysalisbury** [comment]
I was looking through the code to find a potential problem, and my hunch is a keyword argument difference as well. 
It looks like this code has substantial use of `**kwargs`, and some of those are being explicitly passed, and some are being  implicitly passed to a `super`. I haven't nailed down the cause. I'm still fairly new to ruby myself. 

We are working towards migrating to a newer version of ruby / rails. Is graphql-ruby no longer supporting these older versions of ruby / rails?

**Comment by rmosolgo** [comment]
> reproduce with an older version

No, I couldn't get my Ruby 2.5.x / Rails 5.2.x setup working 😖  

> supporting these older versions of ruby / rails?

I _do_ run CI on this Rails 5.2 and Ruby 2.4, but apparently there's no Ruby 2.5 build: 

https://github.com/rmosolgo/graphql-ruby/blob/79ab2eadbd56602d12b989f3dc361b1212f9cddf/.github/workflows/ci.yaml#L39-L52

**Comment by gkampjes** [comment]
It looks like this bug has been fixed by #3917 

I couldn't see why that would be the case, so I did some digging. It turns out there's a bug in Ruby 2.5 (but not < 2.5) for methods with more than 32 keyword args: https://bugs.ruby-lang.org/issues/14373

`GraphQL::Schema::Field#initialize` had 33 kwargs, but now has only 30.

**Comment by rmosolgo** [comment]
Wow! What a doozy, I definitely never heard of it. Thanks for sharing that link. I'll release 2.0.1 soon with that patch. @mckaysalisbury, if you try on a different Ruby version (non-2.5) or graphql-ruby 2.0.1 (or master) and still encounter this problem, please let me know! But I don't plan to investigate further otherwise.
